Repository die-Manufaktur/AI-SEO-Copilot-for-Webflow, pull requests merged in 2025-04, with the labels that each got.

#126 Versioning changes
  SECURITY.md
  package.json
  webflow.json
Labels: documentation

#129 Avoid rate limiting
  .github/workflows/build.yml
Labels: bug

#130 Modified based on pnpm.io docs
  .github/workflows/build.yml
Labels: bug, dependencies

#131 Fix pnpm install process on build
  .github/workflows/build.yml
Labels: bug, dependencies

#133 Add env vars to script
  .github/workflows/build.yml
Labels: bug, dependencies

#134 Tested in dev via a button
  client/src/components/ui/toast.tsx
  client/src/pages/Home.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement

#136 Versioning update
  .github/dependabot.yml
  SECURITY.md
  package.json
  webflow.json
Labels: documentation, dependencies

#138 Switch dependabot to working package ecosystem
  .github/dependabot.yml
Labels: bug, dependencies

#147 Change works on dev and prod
  client/src/pages/Home.tsx
Labels: enhancement

#149 Code minifcation is now at 30%
  workers/index.ts
Labels: enhancement

#150 Error message shows on unpublished pages in dev and prod
  client/src/pages/Home.tsx
  workers/index.ts
Labels: bug, enhancement

#151 Update rating analysis language
  client/src/pages/Home.tsx
  workers/index.ts
Labels: enhancement

#152 Success messages edited, works in dev and prod
  client/src/pages/Home.tsx
  workers/index.ts
Labels: enhancement

#153 Remove all logging from prod
  client/src/lib/api.ts
  client/src/lib/utils.ts
  client/src/pages/Home.tsx
  workers/index.ts
Labels: documentation

#155 Update docs with new version
  README.md
  SECURITY.md
  package.json
  webflow.json
Labels: documentation, dependencies

#162 Create FUNDING.yml
  .github/FUNDING.yml
Labels: documentation, dependencies

#163 157 the recommendation background grey color is missing
  client/src/index.css
  package.json
Labels: bug

#173 Description working as expected
  client/src/lib/api.ts
  client/src/types/global.d.ts
  workers/index.ts
  wrangler.toml
Labels: bug

#175 Keyphrase in H1 fix
  workers/index.ts
Labels: bug

#176 Fixed the keyphrase in introduction check
  client/src/lib/api.ts
  client/src/pages/Home.tsx
  client/src/types/global.d.ts
  package.json
  pnpm-lock.yaml
  workers/index.ts
Labels: bug, enhancement

#178 Fix nextgen image format check
  workers/index.ts
Labels: bug

#182 Fix image alt text recs
  package.json
  pnpm-lock.yaml
  workers/index.ts
Labels: bug, enhancement

#183 OG title, description and image checks all functional in dev and prod
  client/src/lib/types.ts
  client/src/pages/Home.tsx
  package.json
  pnpm-lock.yaml
  workers/index.ts
Labels: bug, enhancement

#184 Fixes schema check in dev and prod
  workers/index.ts
Labels: bug, enhancement

#192 Modify code to handle nested spans in H1s
  package.json
  pnpm-lock.yaml
  workers/index.ts
Labels: bug

#193 Add AI recs back to the OG title-description check
  workers/index.ts
Labels: bug

#196 Icons are now same color and brightness as text in dev and prod
  .github/ISSUE_TEMPLATE/bug_report.yml
  client/src/components/Footer.tsx
  client/src/styles/Footer.css
Labels: enhancement

#198 Latest version 2.4.12beta
  SECURITY.md
  package.json
  webflow.json
Labels: documentation, dependencies

#204 Add background color back in
  client/src/pages/Home.tsx
Labels: bug

#205 Improve suggestion quality and formatting
  client/src/pages/Home.tsx
  package.json
  pnpm-lock.yaml
Labels: bug

#206 Made viewport wider by 40 pixels
  client/manifest.json
  client/src/components/WebflowAppWrapper.tsx
  webflow.json
Labels: bug

#208 Improve AI suggestions
  client/src/pages/Home.tsx
  workers/index.ts
Labels: enhancement

#211 Final optimizations for now
  client/src/pages/Home.tsx
  workers/index.ts
Labels: bug, enhancement

#213 Minor optimizations
  client/index.html
  client/manifest.json
  package.json
  webflow.json
Labels: bug

#221 Modify build script
  .github/workflows/build.yml
  package.json
Labels: bug, enhancement

#222 Split Github workflows into two files
  .github/workflows/deploy.yml
  .github/workflows/pr-check.yml
  package.json
  pnpm-lock.yaml
  scripts/check-env.js
  vitest.config.ts
  workers/index.test.ts
  workers/index.ts
Labels: bug

#223 Add two more tokens to the build script
  .github/workflows/deploy.yml
Labels: bug

#225 More testing for the Home component
  client/src/pages/Home.test.tsx
  client/src/pages/Home.tsx
  client/src/setupTests.ts
  package.json
  pnpm-lock.yaml
  vitest.config.ts
Labels: documentation, dependencies

#226 More tests added
  client/src/pages/Home.test.tsx
  client/src/pages/Home.tsx
Labels: documentation, enhancement

#229 227 the app doesnt get the published page on cms
  client/src/lib/api.ts
  client/src/lib/types.ts
  client/src/lib/utils.ts
  client/src/pages/Home.tsx
  client/src/types/global.d.ts
  vite.config.ts
  workers/index.ts
Labels: bug, enhancement

#231 Update version
  client/manifest.json
  package.json
  webflow.json
Labels: documentation

#257 Fix transparent background on tooltips
  client/src/components/ui/sidebar.tsx
  client/src/components/ui/tooltip.tsx
  package.json
  pnpm-lock.yaml
Labels: bug

#260 Title and description now pull correctly from dynamic CMS fields.
  client/src/lib/types.ts
  client/src/pages/Home.tsx
  package.json
  pnpm-lock.yaml
  shared/types/index.ts
  shared/utils/seoUtils.ts
  workers/index.ts
Labels: bug

#261 233 slug feedback and recommendation
  client/index.html
  client/src/pages/Home.tsx
  package.json
  pnpm-lock.yaml
  vite.config.ts
  vitest.config.ts
Labels: bug

#262 Modify the vite config to set the client folder as the root
  vite.config.ts
Labels: bug

#263 Add build out directory back into config
  vite.config.ts
Labels: bug

#264 More vite config modifying to get the Webflow build to work
  package.json
  pnpm-lock.yaml
  vite.config.ts
Labels: bug

#265 Finally, make the tests run properly again
  vite.config.ts
Labels: bug

#268 Add svg to next-gen image formats
  package.json
  pnpm-lock.yaml
  workers/index.ts
Labels: enhancement

#269 Remove copy button from H2 checks
  client/src/pages/Home.tsx
Labels: enhancement

#270 Fixed image scraping issue
  client/src/lib/api.ts
  client/src/pages/Home.tsx
  workers/index.ts
Labels: bug

#271 Fix a number of minor style bugs
  client/src/components/ui/scroll-area.tsx
  client/src/index.css
  client/src/pages/Home.tsx
Labels: bug

#272 Fix positioning of copy button tooltip
  client/src/components/ui/copy-tooltip.tsx
  client/src/index.css
  client/src/pages/Home.tsx
Labels: bug

#273 146 testing
  client/src/__mocks__/toast-mock.ts
  client/src/hooks/use-toast.test.tsx
  package.json
  pnpm-lock.yaml
  shared/utils/seoUtils.test.tsx
  shared/utils/test-helpers.ts
Labels: enhancement

#274 Added a few more utility tests, hooks and UI components
  client/src/components/ui/button.test.tsx
  client/src/components/ui/card.test.tsx
  client/src/components/ui/input.test.tsx
  client/src/components/ui/tooltip.test.tsx
  client/src/hooks/use-mobile.test.tsx
Labels: enhancement

#276 More component testing. Over 100 tests!
  client/src/components/ui/copy-tooltip.test.tsx
  client/src/components/ui/dialog.test.tsx
  client/src/components/ui/progress-circle.test.tsx
  package.json
  pnpm-lock.yaml
Labels: enhancement
